name = "my-fastapi-project"
main = "main.py"
compatibility_date = "2024-05-08"
compatibility_flags = [ "python_workers" ]

# เพิ่มส่วนนี้เพื่อให้ระบบติดตั้ง Library อัตโนมัติ
[python_bootstrap]
requirements_path = "requirements.txt"