name = "my-fastapi-project"
main = "main.py"
compatibility_date = "2024-05-08"
compatibility_flags = ["python_workers"]

# บังคับให้ใช้ Python 3.12 เพื่อให้ตรงกับ Runtime ของ Cloudflare
[python]
python_version = "3.12"
requirements_path = "requirements.txt"
